site_name: Python金融风控
site_description: 'PyFRM; python fintech; Python智能金融风控; Python高阶教学'
site_author: 'Devin Mah'
site_url: 'http://pyfrm.com'
site_favicon: 'images/python.ico'
pages:
    - PyFRM: index.md
    - 工程基础:
      - 教材介绍: 工程基础/python-tutorial.md
      - 2.x VS 3.x: 工程基础/python2vs3.md
      - Git使用: 工程基础/git.md
      - 文档工具: 工程基础/docs-tools.md
      - 文件与编码 : 工程基础/python-io.md
      - Email操作 : 工程基础/python-email.md
    - 工程进阶:
      - 数据结构: 工程进阶/data-structure.md
      - 面向对象: 工程进阶/object-oriented.md
      - 控制流程: 工程进阶/control-flow.md
      - 并发技术: 工程进阶/Concurrent.md
      - 函数式编程: 工程进阶/functional-programming.md
    - 工程实践:
      - 最佳实践:
        - 实践栈说明: 最佳实践/best-practice.md
        - DevOps: 最佳实践/best-devops.md
        - 基础服务: 最佳实践/best-base-service.md
        - 数据服务: 最佳实践/best-data-service.md
        - 网络开发: 最佳实践/best-network.md
        - 数据智能: 最佳实践/best-data-insight.md
      - 编程规范 : 工程实践/python-style.md
      - 项目结构: 工程实践/project-structure.md
      - 文档管理: 工程实践/manage-docs.md
      - 设计模式: 工程实践/python-patterns.md
      - 调试测试: 工程实践/debug-test.md
      - 审核上线: 工程实践/review-release.md
    - 数据处理:
      - 关系型数据库 : 数据处理/database.md
      - NoSQL : 数据处理/nosql.md
      - SQL-Query: 数据处理/sql.md
      - Json-Query: 数据处理/json-query.md
      - MySQL实践 : 数据处理/mysql.md
      - MongoDB实践 : 数据处理/mongodb.md
      - Pandas实践 : 数据处理/python-pandas.md
    - Web开发:
      - API介绍 : Web开发/web-api.md
      - RESTful: Web开发/restful.md
      - flask实践 : Web开发/flask.md
      - API文档: Web开发/api-docs.md
      - 异步/队列服务 : Web开发/async.md
      - 前端介绍: Web开发/frontend.md
    - 业务知识:
      - 风控指标: 业务知识/risk-management.md
      - 业务结构: 业务知识/o2o-intro.md
      - 统计学基础: 业务知识/stats-intro.md
      - 征信体系: 业务知识/credit-intro.md
      - 反欺诈: 业务知识/anti-fraud.md
    - 数据科学:
      - 机器学习: 数据科学/machine-learning.md
      - 数据挖掘: 数据科学/data-mining.md
      - 模型分析: 数据科学/data-model.md
      - 模型总结: 数据科学/model_iteration_summary.md
      - XGBoost: 数据科学/xgboost.md
      - sk-learn: 数据科学/sk-learn.md
theme: 'material'
theme_dir: 'theme'
copyright: 'Copyright &copy; 2017 Devin Mah'
repo_name: 'pyfrm/fintech'
repo_url: 'https://github.com/pyfrm/fintech'
extra:
  palette:
    primary: 'cyan'
    accent: 'light blue'
  social:
    - type: 'github'
      link: 'https://github.com/madre'
    - type: 'twitter'
      link: 'https://twitter.com/madre0205'
    - type: 'weibo'
      link: 'http://www.weibo.com/madeling/'
  markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - toc(permalink=true)
